
spring:
  application:
    name: mima-kafka-boot-streams
  jmx:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    stream:
      function:
        definition: processMimacom
        bindings:
          processMimacom-in-0: ${app.kafka.topic.input.first.name}
          processMimacom-in-1: ${app.kafka.topic.input.second.name}
          processMimacom-out-0: ${app.kafka.topic.output.name}

      kafka:
        streams:
          binder:
            applicationId: processMimacom-stream-service
            deserializationExceptionHandler: logAndContinue
            configuration:
              spring.json.trusted.packages: '*'
              spring.json.use.type.headers: false
              commit.interval.ms: 100
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            brokers: localhost:9092
            consumer-properties:
              spring.json.trusted.packages: '*'
              spring.json.use.type.headers: false

  json:
    trusted:
      packages: '*'

management:
  endpoint:
    health:
      show-details: always
    jolokia:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
# TODO create ConfigurationProperties and replace @Value wiring in code
app:
  kafka:
    topic:
      input:
        first:
          name: topic_combination_to_consume_from
        second:
          name: topic_decay_to_consume_from
      output:
        name: topic_output_to_produce_to
